name: Python Script

on:
  schedule:
    - cron: '0 0 * * *' # 每天UTC时间0点执行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main # 分支名称
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.6' # 选择Python版本
    - name: Install dependencies
      run: pip3 install -r requirements.txt
    - name: Run script
      run: python china_cidr.py # 执行Python脚本

    - name: Set up Git
        run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -a -m "Auto commit"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main