name: Python Script

on:
  schedule:
    - cron: '0 0 * * *' # 每天UTC时间0点执行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main # 分支名称
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.6' # 选择Python版本
    - name: Run script
      run: python china_cidr.py # 执行Python脚本
    - name: Commit files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'GitHub Actions Update cidr files' # 提交信息
        commit_options: '--no-verify'
        file_pattern: 'cidrs/*' # 选择需要提交的文件
